name: Deployment workflow
on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    - name: Test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: 51.250.87.15
        username: yc-user
        key: ${{ secrets.MY_SECRET }}
        port: 22
        script: whoami
    
